package view;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author dwiar
 */
public class FrameBeranda extends javax.swing.JFrame {

    /**
     * Creates new form FrameKelolaKamar
     */
    public FrameBeranda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_logout = new javax.swing.JLabel();
        btn_beranda = new javax.swing.JLabel();
        btn_kamar = new javax.swing.JLabel();
        btn_penghuni = new javax.swing.JLabel();
        btn_aplikasi = new javax.swing.JLabel();
        btn_exit = new javax.swing.JLabel();
        beranda_layout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        jPanel1.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 740, -1, 50));

        btn_beranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/beranda-act.png"))); // NOI18N
        jPanel1.add(btn_beranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));

        btn_kamar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kkamar.png"))); // NOI18N
        jPanel1.add(btn_kamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        btn_penghuni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kpenghuni (2).png"))); // NOI18N
        jPanel1.add(btn_penghuni, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, -1, -1));

        btn_aplikasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kpenghuni.png"))); // NOI18N
        jPanel1.add(btn_aplikasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, -1, -1));

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_multiply_35px_1.png"))); // NOI18N
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitMouseClicked(evt);
            }
        });
        jPanel1.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 10, 40, -1));

        beranda_layout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/beranda-layout_1.png"))); // NOI18N
        beranda_layout.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                beranda_layoutMouseDragged(evt);
            }
        });
        beranda_layout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                beranda_layoutMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                beranda_layoutMousePressed(evt);
            }
        });
        jPanel1.add(beranda_layout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_exitMouseClicked
    int xx, xy;
    private void beranda_layoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beranda_layoutMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_beranda_layoutMouseClicked

    private void beranda_layoutMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beranda_layoutMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_beranda_layoutMouseDragged

    private void beranda_layoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beranda_layoutMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_beranda_layoutMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameBeranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameBeranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameBeranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameBeranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameBeranda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel beranda_layout;
    private javax.swing.JLabel btn_aplikasi;
    private javax.swing.JLabel btn_beranda;
    private javax.swing.JLabel btn_exit;
    private javax.swing.JLabel btn_kamar;
    private javax.swing.JLabel btn_logout;
    private javax.swing.JLabel btn_penghuni;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
